# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c843bc25a8d3365e6e7d36ec657387b"
application_url = "https://bowl-revision-fax-sent.trycloudflare.com"
embedded = true
name = "amazon-importer"
handle = "amazon-importer-16"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_locations"

[auth]
redirect_urls = [
  "https://bowl-revision-fax-sent.trycloudflare.com/auth/callback",
  "https://bowl-revision-fax-sent.trycloudflare.com/auth/shopify/callback",
  "https://bowl-revision-fax-sent.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "nam-oct.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
